name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Cypress run
        uses: cypress-io/github-action@v5.3.0
        with:
          browser: chrome
          start: npm run headlessChrome
          spec: cypress/telnyxTest/telnyx.spec.cy.js
