name: Telnyx Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5.1.0
        with:
          build: npm run build
          start: npm start
